[package]
name = "peace_item_sh_sync_cmd"
version = "0.0.9"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "Manages a synchronization shell command for the peace framework"
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_item_sh_sync_cmd/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = true
test = false

[dependencies]
chrono = { version = "0.4.24", default-features = false, features = ["clock", "serde"] }
miette = { workspace = true, optional = true }
peace = { path = "../..", version = "0.0.9", default-features = false }
serde = { version = "1.0.159", features = ["derive"] }
thiserror = "1.0.40"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["net", "time", "rt"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true }

[features]
default = []
error_reporting = ["peace/error_reporting"]
output_progress = ["peace/output_progress"]
