[package]
name = "download"
version = "0.0.9"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "Peace framework file download example"
repository = "https://github.com/azriel91/peace"
license = "MIT OR Apache-2.0"
publish = false

[[bin]]
name = "download"
test = false

[lib]
doctest = false
test = false
crate-type = ["cdylib", "rlib"]

[dependencies]
peace = { path = "../..", default-features = false }
peace_items = { path = "../../items", features = ["file_download"] }
thiserror = "1.0.40"
url = { version = "2.3.1", features = ["serde"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = { version = "4.2.1", features = ["derive"] }
tokio = { workspace = true, features = ["net", "time", "rt"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
serde-wasm-bindgen = "0.5.0"
tokio = { workspace = true }
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
js-sys = "0.3.61"
web-sys = "0.3.61"

[features]
default = []
error_reporting = ["peace/error_reporting", "peace_items/error_reporting"]
output_colorized = ["peace/output_colorized"]
output_json = ["peace/output_json"]
output_progress = ["peace/output_progress", "peace_items/output_progress"]
