[package]
name = "download"
version = "0.0.3"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
publish = false

[[bin]]
name = "download"
test = false

[lib]
doctest = false
test = false
crate-type = ["cdylib", "rlib"]

[dependencies]
bytes = "1.2.1"
clap = { version = "4.0.13", features = ["derive"] }
console_error_panic_hook = "0.1.7"
futures = "0.3.24"
peace = { path = "../.." }
reqwest = { version = "0.11.12", features = ["stream"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_yaml = "0.9.13"
thiserror = "1.0.37"
url = { version = "2.3.1", features = ["serde"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.21.2", features = ["fs", "io-std", "io-util", "rt"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
serde-wasm-bindgen = "0.4.5"
tokio = { version = "1.21.2", features = ["io-util"] }
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
js-sys = "0.3.60"
web-sys = "0.3.60"
