[package]
name = "download"
version = "0.0.2"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"

[[bin]]
name = "download"
test = false

[lib]
doctest = false
test = false
crate-type = ["cdylib", "rlib"]

[dependencies]
bytes = "1.1.0"
clap = { version = "3.2.16", features = ["derive"] }
console_error_panic_hook = "0.1.7"
futures = "0.3.21"
peace = { path = "../.." }
reqwest = { version = "0.11.11", features = ["stream"] }
serde = { version = "1.0.139", features = ["derive"] }
serde_yaml = "0.8.26"
thiserror = "1.0.31"
url = "2.2.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.20.0", features = ["fs", "io-std", "io-util", "rt"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.82", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.32"
js-sys = "0.3.59"
web-sys = "0.3.59"
