[package]
name = "download"
version = "0.0.11"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "Peace framework file download example"
repository = "https://github.com/azriel91/peace"
license = "MIT OR Apache-2.0"
publish = false

[[bin]]
name = "download"
test = false

[lib]
doctest = false
test = false
crate-type = ["cdylib", "rlib"]

[dependencies]
peace = { path = "../..", default-features = false }
peace_items = { path = "../../items", features = ["file_download"] }
thiserror = "1.0.40"
url = { version = "2.4.0", features = ["serde"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = { version = "4.3.8", features = ["derive"] }
tokio = { version = "1.28.2", features = ["net", "time", "rt"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
serde-wasm-bindgen = "0.5.0"
tokio = "1.28.2"
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
js-sys = "0.3.64"
web-sys = "0.3.64"

[features]
default = []
error_reporting = ["peace/error_reporting", "peace_items/error_reporting"]
output_progress = ["peace/output_progress", "peace_items/output_progress"]
