[package]
name = "peace"
description = "zero stress automation"
documentation = "https://docs.rs/peace/"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
doctest = true
test = false
crate-type = ["cdylib", "rlib"]

[dependencies]
miette = { workspace = true, optional = true }
peace_cfg = { workspace = true }
peace_cmd_model = { workspace = true }
peace_cmd = { workspace = true }
peace_cmd_rt = { workspace = true }
peace_data = { workspace = true }
peace_diff = { workspace = true }
peace_fmt = { workspace = true }
peace_params = { workspace = true }
peace_resources = { workspace = true }
peace_rt = { workspace = true }
peace_rt_model = { workspace = true }

[features]
default = []
error_reporting = [
    "dep:miette",
    "miette?/fancy",
    "peace_cmd_model/error_reporting",
    "peace_cmd_rt/error_reporting",
    "peace_params/error_reporting",
    "peace_rt/error_reporting",
    "peace_rt_model/error_reporting",
]
output_in_memory = ["peace_rt_model/output_in_memory"]
output_progress = [
    "peace_cmd_rt/output_progress",
    "peace_cfg/output_progress",
    "peace_rt/output_progress",
    "peace_rt_model/output_progress",
]

[workspace]
members = [
    "crate/*",
    "items",
    "workspace_tests",
    "examples/*",
]

[workspace.package]
version = "0.0.11"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
homepage = "https://peace.mk"
repository = "https://github.com/azriel91/peace"
readme = "README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# Peace crates.
peace = { path = ".", version = "0.0.11", default-features = false }

peace_cfg = { path = "crate/cfg", version = "0.0.11" }
peace_cmd_model = { path = "crate/cmd_model", version = "0.0.11" }
peace_cmd = { path = "crate/cmd", version = "0.0.11" }
peace_cmd_rt = { path = "crate/cmd_rt", version = "0.0.11" }
peace_code_gen = { path = "crate/code_gen", version = "0.0.11" }
peace_core = { path = "crate/core", version = "0.0.11" }
peace_data = { path = "crate/data", version = "0.0.11" }
peace_data_derive = { path = "crate/data_derive", version = "0.0.11" }
peace_diff = { path = "crate/diff", version = "0.0.11" }
peace_fmt = { path = "crate/fmt", version = "0.0.11" }
peace_params = { path = "crate/params", version = "0.0.11" }
peace_params_derive = { path = "crate/params_derive", version = "0.0.11" }
peace_resources = { path = "crate/resources", version = "0.0.11" }
peace_rt = { path = "crate/rt", version = "0.0.11" }
peace_rt_model = { path = "crate/rt_model", version = "0.0.11" }
peace_rt_model_core = { path = "crate/rt_model_core", version = "0.0.11" }
peace_rt_model_hack = { path = "crate/rt_model_hack", version = "0.0.11" }
peace_rt_model_native = { path = "crate/rt_model_native", version = "0.0.11" }
peace_rt_model_web = { path = "crate/rt_model_web", version = "0.0.11" }
peace_static_check_macros = { path = "crate/static_check_macros", version = "0.0.11" }

# Item crates
peace_items = { path = "items", version = "0.0.11" }

peace_item_blank = { path = "items/blank", version = "0.0.11" }
peace_item_file_download = { path = "items/file_download", version = "0.0.11" }
peace_item_sh_cmd = { path = "items/sh_cmd", version = "0.0.11" }
peace_item_tar_x = { path = "items/tar_x", version = "0.0.11" }

# Dependencies used by framework and item crates.
#
# This does not include examples' dependencies, because we want it to be easy for
# developers to see the dependencies to create an automation tool.
async-trait = "0.1.73"
base64 = "0.21.4"
bytes = "1.5.0"
cfg-if = "1.0.0"
chrono = { version = "0.4.31", default-features = false, features = ["clock", "serde"] }
console = "0.15.7"
derivative = "2.2.0"
diff-struct = "0.5.3"
downcast-rs = "1.2.0"
dyn-clone = "1.0.14"
enser = "0.1.4"
erased-serde = "0.3.31"
fn_graph = { version = "0.8.6", features = ["resman"] }
futures = "0.3.28"
heck = "0.4.1"
indexmap = "2.0.0"
indicatif = "0.17.7"
miette = "5.10.0"
pretty_assertions = "1.4.0"
proc-macro2 = "1.0.67"
quote = "1.0.33"
reqwest = "0.11.20"
resman = "0.17.0"
serde = "1.0.188"
serde-wasm-bindgen = "0.6.0"
serde_json = "1.0.107"
serde_yaml = "0.9.25"
syn = "2.0.37"
tar = "0.4.40"
tempfile = "3.8.0"
thiserror = "1.0.48"
tokio = "1.32.0"
tokio-util = "0.7.9"
tynm = "0.1.8"
type_reg = { version = "0.6.2", features = ["debug", "untagged", "ordered"] }
url = "2.4.1"
wasm-bindgen = "0.2.87"
web-sys = "0.3.64"
