[package]
name = "peace"
version = "0.0.9"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "zero stress automation"
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace/"
readme = "README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = true
test = false
crate-type = ["cdylib", "rlib"]

[dependencies]
miette = { workspace = true, optional = true }
peace_cfg = { path = "crate/cfg", version = "0.0.9" }
peace_cmd = { path = "crate/cmd", version = "0.0.9" }
peace_data = { path = "crate/data", version = "0.0.9" }
peace_diff = { path = "crate/diff", version = "0.0.9" }
peace_fmt = { path = "crate/fmt", version = "0.0.9" }
peace_params = { path = "crate/params", version = "0.0.9" }
peace_resources = { path = "crate/resources", version = "0.0.9" }
peace_rt = { path = "crate/rt", version = "0.0.9" }
peace_rt_model = { path = "crate/rt_model", version = "0.0.9" }

[workspace]
members = [
    "crate/*",
    "item_specs",
    "workspace_tests",
    "examples/*",
]

[workspace.dependencies]
cfg-if = "1.0.0"
chrono = { version = "0.4.24", default-features = false, features = ["clock", "serde"] }
derivative = "2.2.0"
indexmap = "1.9.3"
indicatif = { version = "0.17.3" }
miette = { version = "5.7.0" }
tar = "0.4.38"
tokio = "1.27.0"
tynm = "0.1.7"
type_reg = { version = "0.5.0", features = ["debug", "untagged", "ordered"] }

[features]
default = []
error_reporting = [
    "dep:miette",
    "miette?/fancy",
    "peace_params/error_reporting",
    "peace_rt/error_reporting",
    "peace_rt_model/error_reporting",
]
output_colorized = ["peace_rt_model/output_colorized"]
output_in_memory = ["peace_rt_model/output_in_memory"]
output_json = ["peace_rt_model/output_json"]
output_progress = [
    "peace_cfg/output_progress",
    "peace_rt/output_progress",
    "peace_rt_model/output_progress",
]
