[package]
name = "peace"
version = "0.0.4"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "zero stress automation"
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace/"
readme = "README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = true
test = false
crate-type = ["cdylib", "rlib"]

[dependencies]
peace_cfg = { path = "crate/cfg", version = "0.0.4" }
peace_data = { path = "crate/data", version = "0.0.4" }
peace_diff = { path = "crate/diff", version = "0.0.4" }
peace_resources = { path = "crate/resources", version = "0.0.4" }
peace_rt = { path = "crate/rt", version = "0.0.4" }
peace_rt_model = { path = "crate/rt_model", version = "0.0.4" }
miette = { workspace = true, optional = true }

[workspace]
members = [
    "crate/*",
    "item_specs",
    "workspace_tests",
    "examples/*",
]

[workspace.dependencies]
miette = { version = "5.4.1" }
derivative = "2.2.0"

[features]
default = ["error_reporting", "output_colorized"]
error_reporting = ["dep:miette", "miette?/fancy", "peace_rt/error_reporting", "peace_rt_model/error_reporting"]
output_colorized = ["peace_rt_model/output_colorized"]
output_json = ["peace_rt_model/output_json"]
