[package]
name = "zzzz"
version = "0.0.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "Automate with your eyes closed."
repository = "https://github.com/azriel91/zzzz"
documentation = "https://docs.rs/zzzz/"
readme = "README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = true
test = false

[dependencies]
zzzz_rt_logic = { path = "crate/rt_logic", version = "0.0.0" }

[workspace]
members = ["crate/*", "workspace_tests"]
