[package]
name = "peace"
version = "0.0.2"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "zero stress automation"
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace/"
readme = "README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = true
test = false

[dependencies]
peace_cfg = { path = "crate/cfg", version = "0.0.2" }
peace_data = { path = "crate/data", version = "0.0.2" }
peace_diff = { path = "crate/diff", version = "0.0.2" }
peace_resources = { path = "crate/resources", version = "0.0.2" }
peace_rt = { path = "crate/rt", version = "0.0.2" }
peace_rt_model = { path = "crate/rt_model", version = "0.0.2" }

[dev-dependencies]
bytes = "1.1.0"
clap = { version = "3.2.16", features = ["derive"] }
futures = "0.3.21"
reqwest = { version = "0.11.11", features = ["stream"] }
serde = { version = "1.0.139", features = ["derive"] }
serde_yaml = "0.8.26"
thiserror = "1.0.31"
tokio = { version = "1.20.0", features = ["fs", "io-std", "io-util", "rt"] }
url = "2.2.2"

[workspace]
members = ["crate/*", "workspace_tests"]
