[package]
name = "peace_rt"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
version = "0.0.6"
edition = "2021"
description = "Runtime logic for the peace automation library."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_rt/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
cfg-if = { workspace = true }
futures = "0.3.26"
miette = { workspace = true, optional = true }
peace_cfg = { path = "../cfg", version = "0.0.6" }
peace_cmd = { path = "../cmd", version = "0.0.6" }
peace_resources = { path = "../resources", version = "0.0.6" }
peace_rt_model = { path = "../rt_model", version = "0.0.6" }
peace_rt_model_core = { path = "../rt_model_core", version = "0.0.6" }
serde = "1.0.152"
serde_yaml = "0.9.17"
tokio = { workspace = true, features = ["sync"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["fs", "io-util"] }
tokio-util = { version = "0.7.7", features = ["io", "io-util"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
peace_rt_model_web = { path = "../rt_model_web", version = "0.0.6" }
wasm-bindgen = { version = "0.2.84", features = ["serde-serialize"] }
web-sys = { version = "0.3.61", features = ["Storage", "Window"] }

[features]
default = []
error_reporting = ["dep:miette", "peace_rt_model/error_reporting"]
output_progress = [
    "peace_cfg/output_progress",
    "peace_cmd/output_progress",
    "peace_rt_model/output_progress",
    "peace_rt_model_core/output_progress",
]
