[package]
name = "peace_rt"
description = "Runtime logic for the peace automation library."
documentation = "https://docs.rs/peace_rt/"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
doctest = false
test = false

[dependencies]
cfg-if = { workspace = true }
futures = "0.3.28"
miette = { workspace = true, optional = true }
peace_cfg = { path = "../cfg", version = "0.0.10" }
peace_cmd = { path = "../cmd", version = "0.0.10" }
peace_params = { path = "../params", version = "0.0.10" }
peace_resources = { path = "../resources", version = "0.0.10" }
peace_rt_model = { path = "../rt_model", version = "0.0.10" }
peace_rt_model_core = { path = "../rt_model_core", version = "0.0.10" }
serde = "1.0.159"
serde_yaml = "0.9.21"
tokio = { workspace = true, features = ["sync"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["fs", "io-util"] }
tokio-util = { version = "0.7.7", features = ["io", "io-util"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
peace_rt_model_web = { path = "../rt_model_web", version = "0.0.10" }
wasm-bindgen = { version = "0.2.84", features = ["serde-serialize"] }
web-sys = { version = "0.3.61", features = ["Storage", "Window"] }

[features]
default = []
error_reporting = ["dep:miette", "peace_rt_model/error_reporting"]
output_progress = [
    "peace_cfg/output_progress",
    "peace_cmd/output_progress",
    "peace_rt_model/output_progress",
    "peace_rt_model_core/output_progress",
]
