[package]
name = "peace_cmd"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
version = "0.0.6"
edition = "2021"
description = "Command structure for the Peace framework."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_cmd/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
indexmap = { workspace = true }
peace_code_gen = { path = "../code_gen", version = "0.0.6" }
peace_core = { path = "../core", version = "0.0.6" }
peace_resources = { path = "../resources", version = "0.0.6" }
peace_rt_model = { path = "../rt_model", version = "0.0.6" }
serde = { version = "1.0.152" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["fs"] }

[features]
default = []
