[package]
name = "peace_item_spec_file_download"
version = "0.0.5"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "Manages downloading a file for the peace framework"
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_item_spec_file_download/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
bytes = "1.3.0"
futures = "0.3.25"
miette = { workspace = true, optional = true }
peace = { path = "../..", version = "0.0.5" }
reqwest = { version = "0.11.13", features = ["stream"] }
serde = { version = "1.0.151", features = ["derive"] }
thiserror = "1.0.38"
url = { version = "2.3.1", features = ["serde"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.23.0", features = ["net", "time", "rt"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1.23.0" }

[features]
default = []
error_reporting = ["peace/error_reporting"]
