[book]
authors = ["Azriel Hoh"]
language = "en"
multilingual = false
src = "src"
title = "The Peace Framework"

[rust]
edition = "2021"

[preprocessor.graphviz]
command = "mdbook-graphviz"

[output.html]
cname = "peace.mk"
git-repository-url = "https://github.com/azriel91/peace"
edit-url-template = "https://github.com/azriel91/peace/edit/main/doc/{path}"
