[package]
name = "peace_item_sh_cmd"
description = "Manages running a shell command for the peace framework"
documentation = "https://docs.rs/peace_item_sh_cmd/"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
doctest = true
test = false

[dependencies]
chrono = { version = "0.4.24", default-features = false, features = ["clock", "serde"] }
derivative = { workspace = true }
miette = { workspace = true, optional = true }
peace = { path = "../..", version = "0.0.10", default-features = false }
serde = { version = "1.0.159", features = ["derive"] }
thiserror = "1.0.40"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["process"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { workspace = true }

[features]
default = []
error_reporting = ["peace/error_reporting"]
output_progress = ["peace/output_progress"]
