[package]
name = "peace_cfg"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
version = "0.0.5"
edition = "2021"
description = "Configuration model for the peace automation framework."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_cfg/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
async-trait = "0.1.60"
peace_core = { path = "../core", version = "0.0.5" }
peace_data = { path = "../data", version = "0.0.5" }
peace_resources = { path = "../resources", version = "0.0.5" }
serde = { version = "1.0.152", features = ["derive"] }

[features]
default = []
output_progress = ["peace_core/output_progress"]
