[package]
name = "peace_cfg"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
version = "0.0.1"
edition = "2021"
description = "Configuration model for the peace automation framework."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_cfg/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
async-trait = "0.1.56"
fn_graph = { version = "0.5.2", features = ["resman"] }
peace_data = { path = "../data", version = "0.0.1" }
peace_diff = { path = "../diff", version = "0.0.1" }
peace_full_spec_id_macro = { path = "../full_spec_id_macro", version = "0.0.1" }
serde = "1.0.138"
