[package]
name = "workspace_tests"
version = "0.0.5"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "Tests for the peace automation library."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace/"
readme = "../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"
publish = false

[lib]
doctest = false
test = true

[dev-dependencies]
diff-struct = "0.5.1"
peace = { path = "..", version = "0.0.5" }
peace_item_specs = { path = "../item_specs", version = "0.0.5" }
pretty_assertions = "1.3.0"
serde = { version = "1.0.151", features = ["derive"] }
serde_yaml = "0.9.16"
tar = { workspace = true }
tempfile = "3.3.0"
thiserror = "1.0.38"
tokio = { version = "1.23.0", features = ["rt", "macros"] }

[features]
default = ["item_specs"]

# `peace` features
error_reporting = ["peace/error_reporting"]
output_colorized = ["peace/output_colorized"]
output_json = ["peace/output_json"]

# `peace_item_specs` features
item_specs = [
    "peace_item_specs/file_download",
    "peace_item_specs/sh_cmd",
    "peace_item_specs/sh_sync_cmd",
    "peace_item_specs/tar_x",
]
