[package]
name = "workspace_tests"
version = "0.0.2"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "Tests for the peace automation library."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace/"
readme = "../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"
publish = false

[lib]
doctest = false
test = true

[dev-dependencies]
diff-struct = "0.4.2"
peace = { path = "..", version = "0.0.2" }
serde = { version = "1.0.139", features = ["derive"] }
serde_yaml = "0.8.26"
tempfile = "3.3.0"
thiserror = "1.0.31"
tokio = { version = "1.20.0", features = ["rt", "macros"] }
