[package]
name = "workspace_tests"
version = "0.0.7"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "Tests for the peace automation library."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace/"
readme = "../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"
publish = false

[lib]
doctest = false
test = true

[dev-dependencies]
cfg-if = { workspace = true }
console = "0.15.5"
diff-struct = "0.5.1"
futures = "0.3.26"
peace = { path = "..", version = "0.0.7", default-features = false }
peace_item_specs = { path = "../item_specs", version = "0.0.7" }
pretty_assertions = "1.3.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
serde_yaml = "0.9.17"
tar = { workspace = true }
tempfile = "3.4.0"
thiserror = "1.0.38"
tokio = { workspace = true, features = ["rt", "macros"] }

[features]
default = ["item_specs", "output_in_memory"]

# `peace` features
error_reporting = ["peace/error_reporting"]
output_colorized = ["peace/output_colorized"]
output_in_memory = ["peace/output_in_memory"]
output_json = ["peace/output_json"]
output_progress = ["peace/output_progress", "peace_item_specs/output_progress"]

# `peace_item_specs` features
item_specs = [
    "peace_item_specs/blank",
    "peace_item_specs/file_download",
    "peace_item_specs/sh_cmd",
    "peace_item_specs/sh_sync_cmd",
    "peace_item_specs/tar_x",
]
