[book]
authors = ["Azriel Hoh"]
language = "en"
multilingual = false
src = "src"
title = "The Peace Framework - Business Handbook"

[rust]
edition = "2021"

[preprocessor.graphviz]
command = "mdbook-graphviz"

[output.html]
theme = "theme"
additional-css = ["src/css/layout.css"]
additional-js = ["src/js/highlightjs-line-numbers.min.js"]
cname = "peace.mk"
git-repository-url = "https://github.com/azriel91/peace"
edit-url-template = "https://github.com/azriel91/peace/edit/main/business_handbook/{path}"
site-url = "/business_handbook/" # to work with `peace_website`

[output.html.fold]
enable = true
level = 0
