[package]
name = "peace_rt_model_web"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
version = "0.0.3"
edition = "2021"
description = "Web support for the peace automation framework."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_web_support/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
peace_core = { path = "../core", version = "0.0.3" }
peace_resources = { path = "../resources", version = "0.0.3" }
thiserror = "1.0.35"
serde = "1.0.145"
serde-wasm-bindgen = "0.4.3"
serde_yaml = "0.9.13"
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3.60", features = ["Storage", "Window"] }
