[package]
name = "peace_rt_model_web"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
version = "0.0.10"
edition = "2021"
description = "Web support for the peace automation framework."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_web_support/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
base64 = "0.21.0"
miette = { workspace = true, optional = true }
peace_core = { path = "../core", version = "0.0.10" }
peace_resources = { path = "../resources", version = "0.0.10" }
peace_rt_model_core = { path = "../rt_model_core", version = "0.0.10" }
serde = "1.0.159"
serde-wasm-bindgen = "0.5.0"
serde_json = { version = "1.0.95", optional = true }
serde_yaml = "0.9.21"
thiserror = "1.0.40"
wasm-bindgen = "0.2.84"
web-sys = { version = "0.3.61", features = ["Storage", "Window"] }

[features]
default = []
error_reporting = ["dep:miette", "peace_rt_model_core/error_reporting"]
output_json = ["dep:serde_json"]
output_progress = []
