[package]
name = "peace_rt_model_native"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
version = "0.0.3"
edition = "2021"
description = "Runtime data types for the peace automation framework."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_rt_model_native/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
console = { version = "0.15.2", optional = true }
futures = "0.3.24"
peace_core = { path = "../core", version = "0.0.3" }
peace_resources = { path = "../resources", version = "0.0.3" }
peace_rt_model_core = { path = "../rt_model_core", version = "0.0.3" }
serde = "1.0.145"
serde_yaml = "0.9.13"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["fs", "io-std"] }
tokio-util = { version = "0.7.4", features = ["io", "io-util"] }

[features]
default = []
output_colorized = ["dep:console"]
