[package]
name = "peace_rt_model_native"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
version = "0.0.6"
edition = "2021"
description = "Runtime data types for the peace automation framework."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_rt_model_native/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = true
test = false

[dependencies]
cfg-if = { workspace = true }
console = { version = "0.15.5", optional = true }
futures = "0.3.25"
is-terminal = { version = "0.4.2", optional = true }
miette = { workspace = true, optional = true }
peace_core = { path = "../core", version = "0.0.6" }
peace_resources = { path = "../resources", version = "0.0.6" }
peace_rt_model_core = { path = "../rt_model_core", version = "0.0.6" }
serde = "1.0.152"
serde_json = { version = "1.0.91", optional = true }
serde_yaml = "0.9.16"
thiserror = "1.0.38"
tokio = { workspace = true, features = ["fs", "io-std"] }
tokio-util = { version = "0.7.4", features = ["io", "io-util"] }

[features]
default = []
error_reporting = ["dep:miette", "peace_rt_model_core/error_reporting"]
output_colorized = ["dep:console", "dep:is-terminal"]
output_in_memory = ["peace_rt_model_core/output_in_memory"]
output_json = ["dep:serde_json", "peace_rt_model_core/output_json"]
output_progress = [
    "dep:console",
    "dep:is-terminal",
    "peace_core/output_progress",
    "peace_rt_model_core/output_progress",
]
