[package]
name = "peace_rt_model_native"
description = "Runtime data types for the peace automation framework."
documentation = "https://docs.rs/peace_rt_model_native/"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
doctest = true
test = false

[dependencies]
cfg-if = { workspace = true }
console = { workspace = true, optional = true }
futures = { workspace = true }
is-terminal = { workspace = true, optional = true }
miette = { workspace = true, optional = true }
peace_core = { workspace = true }
peace_fmt = { workspace = true }
peace_resources = { workspace = true }
peace_rt_model_core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-std"] }
tokio-util = { workspace = true, features = ["io", "io-util"] }

[features]
default = []
error_reporting = ["dep:miette", "peace_rt_model_core/error_reporting"]
output_colorized = ["dep:console", "dep:is-terminal"]
output_in_memory = ["peace_rt_model_core/output_in_memory"]
output_json = ["dep:serde_json", "peace_rt_model_core/output_json"]
output_progress = [
    "dep:console",
    "dep:is-terminal",
    "peace_core/output_progress",
    "peace_rt_model_core/output_progress",
]
