[package]
name = "peace_rt_model_native"
description = "Runtime data types for the peace automation framework."
documentation = "https://docs.rs/peace_rt_model_native/"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
doctest = true
test = false

[dependencies]
cfg-if = { workspace = true }
console = { version = "0.15.5", optional = true }
futures = "0.3.28"
is-terminal = { version = "0.4.7", optional = true }
miette = { workspace = true, optional = true }
peace_core = { path = "../core", version = "0.0.10" }
peace_fmt = { path = "../fmt", version = "0.0.10" }
peace_resources = { path = "../resources", version = "0.0.10" }
peace_rt_model_core = { path = "../rt_model_core", version = "0.0.10" }
serde = "1.0.159"
serde_json = { version = "1.0.95", optional = true }
serde_yaml = "0.9.21"
thiserror = "1.0.40"
tokio = { workspace = true, features = ["fs", "io-std"] }
tokio-util = { version = "0.7.7", features = ["io", "io-util"] }

[features]
default = []
error_reporting = ["dep:miette", "peace_rt_model_core/error_reporting"]
output_colorized = ["dep:console", "dep:is-terminal"]
output_in_memory = ["peace_rt_model_core/output_in_memory"]
output_json = ["dep:serde_json", "peace_rt_model_core/output_json"]
output_progress = [
    "dep:console",
    "dep:is-terminal",
    "peace_core/output_progress",
    "peace_rt_model_core/output_progress",
]
