[package]
name = "envman"
version = "0.0.9"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "Peace framework web application lifecycle example"
repository = "https://github.com/azriel91/peace"
license = "MIT OR Apache-2.0"
publish = false

[[bin]]
name = "envman"
test = false

[lib]
doctest = false
test = false
crate-type = ["cdylib", "rlib"]

[dependencies]
aws-config = "0.55.0"
aws-sdk-iam = "0.25.1"
aws-sdk-s3 = "0.25.1"
aws-smithy-http = "0.55.0" # used to reference error type, otherwise not recommended for direct usage
base64 = "0.21.0"
cfg-if = { workspace = true }
chrono = { version = "0.4.24", default-features = false, features = ["clock", "serde"] }
derivative = { workspace = true }
futures = "0.3.28"
md5-rs = "0.1.5"  # WASM compatible, and reads bytes as stream
peace = { path = "../..", default-features = false }
peace_items = { path = "../../items", features = ["file_download", "tar_x"] }
semver = "1.0.17"
serde = { version = "1.0.159", features = ["derive"] }
thiserror = "1.0.40"
url = { version = "2.3.1", features = ["serde"] }
urlencoding = "2.1.2"
whoami = "1.4.0"

# web_server
axum = { version = "0.6.18", optional = true }
dioxus = { version = "0.3.2", optional = true }
dioxus-ssr = { version = "0.3.0", optional = true }
hyper = { version = "0.14.26", optional = true }
tower-http = { version = "0.4.0", optional = true, features = ["fs"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = { version = "4.2.1", features = ["derive"] }
tokio = { workspace = true, features = ["rt", "rt-multi-thread"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
serde-wasm-bindgen = "0.5.0"
tokio = { workspace = true }
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
js-sys = "0.3.61"
web-sys = "0.3.61"

[features]
default = ["web_server"]
error_reporting = [
    "peace/error_reporting",
    "peace_items/error_reporting",
]
output_colorized = ["peace/output_colorized"]
output_json = ["peace/output_json"]
output_progress = [
    "peace/output_progress",
    "peace_items/output_progress",
]
web_server = [
    "dep:axum",
    "dep:dioxus",
    "dep:dioxus-ssr",
    "dep:hyper",
    "dep:tower-http",
]
