[package]
name = "peace_rt_model_core"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
version = "0.0.6"
edition = "2021"
description = "Core runtime traits for the peace automation framework."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_rt_model_core/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
async-trait = "0.1.61"
cfg-if = { workspace = true }
indicatif = { workspace = true, features = ["tokio"] }
miette = { workspace = true, optional = true }
peace_core = { path = "../core", version = "0.0.6", optional = true }
peace_resources = { path = "../resources", version = "0.0.6" }
serde = "1.0.152"
serde_json = { version = "1.0.91", optional = true }
type_reg = { workspace = true, features = ["resman"] }

[features]
default = []
error_reporting = ["dep:miette"]
output_colorized = ["miette?/fancy"]
output_in_memory = ["indicatif/in_memory"]
output_json = ["dep:serde_json"]
output_progress = ["peace_core/output_progress"]
