[package]
name = "peace_rt_model_core"
description = "Core runtime traits for the peace automation framework."
documentation = "https://docs.rs/peace_rt_model_core/"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
doctest = false
test = false

[dependencies]
async-trait = "0.1.68"
cfg-if = { workspace = true }
indicatif = { workspace = true, features = ["tokio"] }
indexmap = { workspace = true }
miette = { workspace = true, optional = true }
peace_core = { path = "../core", version = "0.0.10" }
peace_fmt = { path = "../fmt", version = "0.0.10" }
peace_params = { path = "../params", version = "0.0.10" }
peace_resources = { path = "../resources", version = "0.0.10" }
serde = "1.0.159"
serde_json = { version = "1.0.95", optional = true }
serde_yaml = "0.9.21"
thiserror = "1.0.40"
type_reg = { workspace = true, features = ["resman"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
base64 = "0.21.0"

[features]
default = []
error_reporting = ["dep:miette"]
output_colorized = ["miette?/fancy"]
output_in_memory = ["indicatif/in_memory"]
output_json = ["dep:serde_json"]
output_progress = ["peace_core/output_progress"]
