[package]
name = "peace_rt_model"
description = "Runtime data types for the peace automation framework."
documentation = "https://docs.rs/peace_rt_model/"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[lib]
doctest = false
test = false

[dependencies]
cfg-if = { workspace = true }
dyn-clone = "1.0.11"
erased-serde = "0.3.25"
futures = "0.3.28"
indicatif = { workspace = true, features = ["tokio"] }
miette = { workspace = true, optional = true }
peace_cfg = { path = "../cfg", version = "0.0.10" }
peace_data = { path = "../data", version = "0.0.10" }
peace_fmt = { path = "../fmt", version = "0.0.10" }
peace_params = { path = "../params", version = "0.0.10" }
peace_resources = { path = "../resources", version = "0.0.10" }
peace_rt_model_core = { path = "../rt_model_core", version = "0.0.10" }
peace_rt_model_hack = { path = "../rt_model_hack", version = "0.0.10", optional = true }
serde = "1.0.159"
serde_yaml = "0.9.21"
type_reg = { workspace = true, features = ["resman"] }
tynm = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
peace_rt_model_native = { path = "../rt_model_native", version = "0.0.10" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
peace_rt_model_web = { path = "../rt_model_web", version = "0.0.10" }

[features]
default = []
error_reporting = [
    "dep:miette",
    "peace_params/error_reporting",
    "peace_rt_model_hack/error_reporting",
]
output_colorized = ["peace_rt_model_native/output_colorized"]
output_in_memory = ["peace_rt_model_native/output_in_memory"]
output_json = ["peace_rt_model_hack/output_json"]
output_progress = [
    "peace_cfg/output_progress",
    "peace_rt_model_hack/output_progress"
]
