[package]
name = "peace_rt_model"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
version = "0.0.2"
edition = "2021"
description = "Runtime data types for the peace automation framework."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_rt_model/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
fn_graph = { version = "0.5.2", features = ["resman"] }
futures = "0.3.21"
peace_cfg = { path = "../cfg", version = "0.0.2" }
peace_data = { path = "../data", version = "0.0.2" }
peace_resources = { path = "../resources", version = "0.0.2" }
serde = "1.0.139"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
peace_rt_model_native = { path = "../rt_model_native", version = "0.0.2" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
peace_rt_model_web = { path = "../rt_model_web", version = "0.0.2" }
