[package]
name = "peace_rt_model"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
version = "0.0.3"
edition = "2021"
description = "Runtime data types for the peace automation framework."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_rt_model/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = false
test = false

[dependencies]
fn_graph = { version = "0.5.4", features = ["resman"] }
futures = "0.3.25"
peace_cfg = { path = "../cfg", version = "0.0.3" }
peace_data = { path = "../data", version = "0.0.3" }
peace_resources = { path = "../resources", version = "0.0.3" }
peace_rt_model_core = { path = "../rt_model_core", version = "0.0.3" }
peace_rt_model_hack = { path = "../rt_model_hack", version = "0.0.3", optional = true }
serde = "1.0.147"
serde_yaml = "0.9.14"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
peace_rt_model_native = { path = "../rt_model_native", version = "0.0.3" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
peace_rt_model_web = { path = "../rt_model_web", version = "0.0.3" }

[features]
default = []
error_reporting = ["dep:peace_rt_model_hack"]
output_colorized = ["peace_rt_model_native/output_colorized"]
output_json = ["peace_rt_model_native/output_json", "peace_rt_model_web/output_json"]
