[package]
name = "app_cycle"
version = "0.0.7"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "Peace framework web application lifecycle example"
repository = "https://github.com/azriel91/peace"
license = "MIT OR Apache-2.0"
publish = false

[[bin]]
name = "app_cycle"
test = false

[lib]
doctest = false
test = false
crate-type = ["cdylib", "rlib"]

[dependencies]
aws-config = "0.54.1"
aws-sdk-iam = "0.24.0"
aws-sdk-s3 = "0.24.0"
aws-smithy-http = "0.54.4" # used to reference error type, otherwise not recommended for direct usage
base64 = "0.21.0"
cfg-if = { workspace = true }
derivative = { workspace = true }
futures = "0.3.27"
md5-rs = "0.1.5"  # WASM compatible, and reads bytes as stream
peace = { path = "../..", default-features = false }
peace_item_specs = { path = "../../item_specs", features = ["file_download", "tar_x"] }
semver = "1.0.17"
serde = { version = "1.0.155", features = ["derive"] }
thiserror = "1.0.39"
url = { version = "2.3.1", features = ["serde"] }
urlencoding = "2.1.2"
whoami = "1.4.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = { version = "4.1.8", features = ["derive"] }
tokio = { workspace = true, features = ["rt"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
serde-wasm-bindgen = "0.5.0"
tokio = { workspace = true }
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
js-sys = "0.3.61"
web-sys = "0.3.61"

[features]
default = []
error_reporting = [
    "peace/error_reporting",
    "peace_item_specs/error_reporting",
]
output_colorized = ["peace/output_colorized"]
output_json = ["peace/output_json"]
output_progress = [
    "peace/output_progress",
    "peace_item_specs/output_progress",
]
