[package]
name = "peace_item_spec_sh_cmd"
version = "0.0.5"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "Manages running a shell command for the peace framework"
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_item_spec_sh_cmd/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = true
test = false

[dependencies]
chrono = { version = "0.4.23", default-features = false, features = ["clock", "serde"] }
derivative = { workspace = true }
miette = { workspace = true, optional = true }
peace = { path = "../..", version = "0.0.5" }
serde = { version = "1.0.147", features = ["derive"] }
thiserror = "1.0.37"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.22.0", features = ["process"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1.22.0" }

[features]
default = []
error_reporting = ["peace/error_reporting"]
