[package]
name = "peace_core"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
version = "0.0.5"
edition = "2021"
description = "Low level data types for the peace automation framework."
repository = "https://github.com/azriel91/peace"
documentation = "https://docs.rs/peace_core/"
readme = "../../README.md"
categories = ["asynchronous", "config"]
keywords = ["automation"]
license = "MIT OR Apache-2.0"

[lib]
doctest = true
test = false

[dependencies]
cfg-if = { workspace = true }
chrono = { workspace = true, default-features = false, features = ["clock", "serde"] }
indicatif = { workspace = true }
peace_static_check_macros = { path = "../static_check_macros", version = "0.0.5" }
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.23.0", optional = true, features = ["sync"] }

[features]
default = []
output_progress = ["dep:tokio"]
